### ISSUE TITLE
There's a typo

### ISSUE THREAD

**Issue by wizardbc** [leanprover/lean.js#10]
There is a typo in 'components/lean/config.py', before DOWNLOADS there is a url.

In 'lean-master/src/util/file_lock.cpp', please insert `#include <fcntl.h>`.
And also please remove -j option in 'components/lean_js/config.py'.

Thank you.

**Comment by soonhokong** [comment]
@wizardbc, the problems related to `config.py` are fixed.

**Comment by soonhokong** [comment]
> please insert #include <fcntl.h>

Added to the main repo. See https://github.com/leanprover/lean/commit/f911747b604ed1324bd83fc3d21edc8b67314a2a
