### ISSUE TITLE
make exhausting 14 Gb memory and dies

### ISSUE THREAD

**Issue by vird** [leanprover/lean.js#4]
uname -a

    Linux calculate 3.18.14-calculate #1 SMP PREEMPT Sun May 31 08:39:04 UTC 2015 x86_64 AMD A10-7800 Radeon R7, 12 Compute Cores 4C+8G AuthenticAMD GNU/Linux
NOTE: No, I don't want reference issue 1, sorry for that
https://gist.github.com/vird/26c13767db5d0092c522

problem is here
python build_all.py lean

make[1]: Entering directory '/opt/ext/user_make/lean.js/build/lean/source/lean-master'
make[2]: Entering directory '/opt/ext/user_make/lean.js/build/lean/source/lean-master'
make[3]: Entering directory '/opt/ext/user_make/lean.js/build/lean/source/lean-master'
make[3]: Entering directory '/opt/ext/user_make/lean.js/build/lean/source/lean-master'
make[3]: Entering directory '/opt/ext/user_make/lean.js/build/lean/source/lean-master'
total 40 Entering directory '/opt/ext/user_make/lean.js/build/lean/source/lean-master'

**Comment by vird** [comment]
possible problem@build_all.py
build_component(component, INCLUDES_DIR, LIBS_DIR)

  cd build/lean/source/lean-master
  make

seems works and not dies.

**Comment by soonhokong** [comment]
Thanks for your attention on the project.

According to the result of your `uname -a` output, it seems that you're compiling lean.js on a 64-bit machine. If so, I'm sorry to tell you that it doesn't work on a 64-bit machine as noted in [READEME.md](https://github.com/leanprover/lean.js/blob/master/README.md).

**Comment by wizardbc** [comment]
I had the same problem with 32-bit machine.
I think it is something wrong in process of `make -j`.
I've added some integer after -j option in 'components/lean/config.py'

```shellscript
MAKE_CMD = 'emmake make -j7'
```

And then it works fine.

**Comment by soonhokong** [comment]
@wizardbc, thanks!
